// Writes index.html, timing.js and compositions/panel.html from timing.json
// and panel.json. A beat with compositions/<id>.html mounts it; any other beat
// mounts the placeholder, so the cut is timed end to end.
// Run from film/deck/videos/night: node scripts/build.mjs [--final]
import fs from "node:fs";

const T = JSON.parse(fs.readFileSync("timing.json", "utf8"));
const P = JSON.parse(fs.readFileSync("panel.json", "utf8"));
const final = process.argv.includes("--final");
const missing = T.beats.filter((b) => !fs.existsSync(`compositions/${b.id}.html`));
if (final && missing.length) { console.error("placeholders left:", missing.map((b) => b.id).join(", ")); process.exit(1); }

fs.writeFileSync("timing.js", `// Generated by scripts/build.mjs from timing.json.\nwindow.TIMING = ${JSON.stringify({ cues: Object.fromEntries(T.beats.map((b) => [b.id, { start: b.start, dur: b.dur, ...(b.cues || {}) }])) })};\n`);

const beat = (b) => {
  const has = fs.existsSync(`compositions/${b.id}.html`);
  const src = has ? `compositions/${b.id}.html` : "compositions/placeholder.html";
  const vars = has ? "" : ` data-variable-values='${JSON.stringify({ slot: b.id, shows: b.shows.replace(/'/g, "’") })}'`;
  return `    <div id="el-${b.id}" data-composition-id="${b.id}" data-composition-src="${src}" data-start="${b.start}" data-duration="${b.dur}" data-track-index="1"${vars}></div>`;
};

// The panel: each run's calls, quoted from panel.json, typed on at timing.json's times.
const runs = T.panel.map((r) => {
  const calls = P[r.run].calls;
  if (calls.length !== r.lines.length) throw new Error(`${r.run}: ${calls.length} calls in the trace, ${r.lines.length} times in timing.json`);
  return { run: r.run, at: r.at, case: P[r.run].case, lines: calls.map((c, i) => ({ op: c.op, to: c.to, at: r.lines[i] })) };
});
const panel = `<template id="panel-template">
  <div data-composition-id="panel" data-width="1920" data-height="1080" data-duration="${T.duration}" style="position:absolute;inset:0;pointer-events:none;z-index:30">
    <style>
      /* The clock has its own row, so a long heading never runs into it. */
      #np { position: absolute; left: 96px; top: 72px; width: 680px; height: 864px; padding: 40px 48px; border-radius: 28px; }
      #np .ck { position: relative; height: 56px; }
      #np .ck > span { position: absolute; left: 0; top: 0; font: 500 44px/56px var(--mono); letter-spacing: -0.02em; color: var(--ink); white-space: nowrap; }
      #np .hd { position: relative; height: 72px; margin-top: 8px; }
      #np .hd > span { position: absolute; left: 0; top: 0; font: 500 55px/1.09 var(--display); letter-spacing: -0.031em; color: var(--ink); white-space: nowrap; }
      #np .run { position: relative; height: 52px; margin-top: 8px; }
      #np .run > span { position: absolute; left: 0; top: 0; font: 500 37px/1.3 var(--sans); letter-spacing: -0.012em; color: var(--mute); white-space: nowrap; }
      #np hr { border: 0; height: 1px; background: var(--hair); margin: 16px 0 14px; }
      #np .ls { position: relative; }
      #np .ls > div { position: absolute; left: 0; top: 0; width: 100%; }
      #np .l { height: 48px; display: flex; align-items: baseline; gap: 14px; white-space: nowrap; color: var(--ink); }
      #np .l b { font: 500 37px/48px var(--mono); letter-spacing: -0.02em; color: var(--ink); font-weight: 500; }
      #np .l i { font: 500 37px/48px var(--sans); font-style: normal; letter-spacing: -0.012em; color: var(--mute); }
    </style>
    <div id="np" class="card">
      <div class="ck" id="np-ck"></div>
      <div class="hd" id="np-hd"></div>
      <div class="run" id="np-run"></div>
      <hr>
      <div class="ls" id="np-ls"></div>
    </div>
    <script>
      // Generated by scripts/build.mjs. Tool names and recipients only, never message text.
      // Base44's prompt box (film/LOOK.md, night row; strips 11, 12, 18): each call types
      // behind a cursor, one line at a time; headings cut in a word a tick; the clock steps
      // on the tick into each new time; a new run clears the list by a hard cut.
      (function () {
        const M = MOTION, TITLES = ${JSON.stringify(T.titles)}, RUNS = ${JSON.stringify(runs)};
        const tl = gsap.timeline({ paused: true });
        const hd = document.getElementById("np-hd"), run = document.getElementById("np-run"), ls = document.getElementById("np-ls");
        const ck = document.getElementById("np-ck");
        const span = (parent, text) => { const e = document.createElement("span"); e.textContent = text; parent.appendChild(e); return e; };
        // Clock times as minutes since noon, so 8:30 PM < 1:00 AM < 1:00 PM next day.
        const mins = (c) => { const [, h, m, ap] = c.match(/(\\d+):(\\d+) (AM|PM)/); let x = (+h % 12) * 60 + +m + (ap === "AM" ? 720 : 0); return x; };
        const fmt = (x) => { x = ((x % 1440) + 1440) % 1440; const ap = x < 720 ? "PM" : "AM", h = Math.floor(x / 60) % 12 || 12, m = x % 60; return h + ":" + String(m).padStart(2, "0") + " " + ap; };
        // Anything cued at 0 is on the first frame, which is also the poster.
        let ph = null, pc = null, cut = {};
        TITLES.forEach((t) => {
          if (!ph || ph.textContent !== t.title) {
            const h = span(hd, t.title);
            if (t.at <= 0) gsap.set(h, { autoAlpha: 1 });
            else { M.hide(h); M.cut(tl, ph, t.at, false); M.cut(tl, h, t.at); M.words(tl, M.wordsOf(h), t.at); }
            ph = h;
          }
          if (pc && pc.textContent === t.clock) return;
          const c = span(ck, t.clock);
          if (!pc) { gsap.set(c, { autoAlpha: 1 }); pc = c; return; }
          M.hide(c);
          // the tumble: three in-between times, one a tick, landing on the new time at t.at
          const a = mins(pc.textContent), b = mins(t.clock) + (mins(t.clock) < a ? 1440 : 0), steps = [1, 2, 3].map((k) => span(ck, fmt(Math.round(a + ((b - a) * k) / 4))));
          M.hide(steps);
          M.cut(tl, pc, t.at - 3 * M.TICK, false);
          M.flash(tl, steps, t.at - 3 * M.TICK);
          M.cut(tl, c, t.at);
          pc = c;
        });
        // Runs: a new run clears the list on one frame; older lines go mute as the next types on.
        let prevBox = null, prevRun = null;
        RUNS.forEach((r) => {
          const box = document.createElement("div"); ls.appendChild(box);
          const rl = span(run, r.run + " · " + r.case + " · Baari-eval");
          if (prevBox) { M.hide([box, rl]); M.swap(tl, [prevBox, prevRun], [box, rl], r.at); }
          const els = r.lines.map((c) => {
            const d = document.createElement("div"); d.className = "l";
            d.innerHTML = "<b></b>" + (c.to ? "<i></i>" : "");
            d.querySelector("b").textContent = c.op;
            if (c.to) d.querySelector("i").textContent = "→ " + c.to;
            box.appendChild(d); return d;
          });
          r.lines.forEach((c, i) => {
            if (c.at > 0) M.type(tl, els[i], c.at, { seed: r.run + i });
            if (i > 0) tl.set(els[i - 1].querySelector("b"), { color: "#6B675F" }, Math.round(c.at * 30) / 30);
          });
          prevBox = box; prevRun = rl;
        });
        tl.set({}, {}, ${T.duration});
        window.__timelines["panel"] = tl;
      })();
    </script>
  </div>
</template>
`;
fs.writeFileSync("compositions/panel.html", panel);

const html = `<!doctype html>
<html lang="en">
<head>
<meta charset="UTF-8" />
<meta name="viewport" content="width=1920, height=1080" />
<title>Baari night</title>
<!-- Generated by scripts/build.mjs from timing.json. Edit timing.json, then rebuild. -->
<link rel="stylesheet" href="shared/theme.css" />
<style>
  html, body { width: 1920px; height: 1080px; overflow: hidden; background: var(--ground); }
  #root { position: relative; width: 100%; height: 100%; overflow: hidden; }
  #root > div[data-composition-src] { position: absolute; inset: 0; }
  .shot { position: absolute; inset: 0; overflow: hidden; }
  #foot { position: absolute; left: 0; right: 0; top: 960px; text-align: center; font: 500 37px/1.3 var(--sans); letter-spacing: -0.012em; color: var(--mute); z-index: 30; }
</style>
<script src="shared/vendor/gsap.min.js"></script>
<script src="motion.js"></script>
<script src="timing.js"></script>
</head>
<body>
  <div id="root" data-composition-id="night" data-width="1920" data-height="1080" data-start="0" data-duration="${T.duration}">
${T.beats.map(beat).join("\n")}
    <div id="el-panel" data-composition-id="panel" data-composition-src="compositions/panel.html" data-start="0" data-duration="${T.duration}" data-track-index="4"></div>
    <div id="foot">App on demo data · tool calls from real runs on AgenticOrg, 4 October</div>
  </div>
  <script>
    window.__timelines["night"] = gsap.timeline({ paused: true });
  </script>
</body>
</html>
`;
fs.writeFileSync("index.html", html);
console.log(`index.html: ${T.beats.length} beats, ${T.duration}s, ${missing.length} placeholders; panel ${runs.map((r) => r.run + " " + r.lines.length).join(", ")}`);
