// Writes index.html, timing.js and compositions/panel.html from timing.json
// and panel.json. A beat with compositions/<id>.html mounts it; any other beat
// mounts the placeholder, so the cut is timed end to end.
// Run from film/deck/videos/night: node scripts/build.mjs [--final]
import fs from "node:fs";

const T = JSON.parse(fs.readFileSync("timing.json", "utf8"));
const P = JSON.parse(fs.readFileSync("panel.json", "utf8"));
const final = process.argv.includes("--final");
const missing = T.beats.filter((b) => !fs.existsSync(`compositions/${b.id}.html`));
if (final && missing.length) { console.error("placeholders left:", missing.map((b) => b.id).join(", ")); process.exit(1); }

fs.writeFileSync("timing.js", `// Generated by scripts/build.mjs from timing.json.\nwindow.TIMING = ${JSON.stringify({ cues: Object.fromEntries(T.beats.map((b) => [b.id, { start: b.start, dur: b.dur, ...(b.cues || {}) }])) })};\n`);

const beat = (b) => {
  const has = fs.existsSync(`compositions/${b.id}.html`);
  const src = has ? `compositions/${b.id}.html` : "compositions/placeholder.html";
  const vars = has ? "" : ` data-variable-values='${JSON.stringify({ slot: b.id, shows: b.shows.replace(/'/g, "’") })}'`;
  return `    <div id="el-${b.id}" data-composition-id="${b.id}" data-composition-src="${src}" data-start="${b.start}" data-duration="${b.dur}" data-track-index="1"${vars}></div>`;
};

// The panel: each run's calls, quoted from panel.json, typed on at timing.json's times.
const runs = T.panel.map((r) => {
  const calls = P[r.run].calls;
  if (calls.length !== r.lines.length) throw new Error(`${r.run}: ${calls.length} calls in the trace, ${r.lines.length} times in timing.json`);
  return { run: r.run, at: r.at, case: P[r.run].case, lines: calls.map((c, i) => ({ op: c.op, to: c.to, at: r.lines[i] })) };
});
const panel = `<template id="panel-template">
  <div data-composition-id="panel" data-width="1920" data-height="1080" data-duration="${T.duration}" style="position:absolute;inset:0;pointer-events:none;z-index:30">
    <style>
      #np { position: absolute; left: 96px; top: 96px; width: 680px; height: 834px; padding: 44px 48px; border-radius: 28px; }
      #np .hd { position: relative; height: 72px; }
      #np .hd > span { position: absolute; left: 0; top: 0; font: 500 55px/1.09 var(--display); letter-spacing: -0.031em; color: var(--ink); white-space: nowrap; opacity: 0; }
      #np .ck { position: absolute; right: 48px; top: 46px; height: 56px; width: 220px; }
      #np .ck > span { position: absolute; right: 0; top: 0; font: 500 44px/56px var(--mono); letter-spacing: -0.02em; color: var(--ink); opacity: 0; }
      #np .run { position: relative; height: 52px; margin-top: 16px; }
      #np .run > span { position: absolute; left: 0; top: 0; font: 500 37px/1.3 var(--sans); letter-spacing: -0.012em; color: var(--mute); white-space: nowrap; opacity: 0; }
      #np hr { border: 0; height: 1px; background: var(--hair); margin: 22px 0 18px; }
      #np .ls { position: relative; }
      #np .ls > div { position: absolute; left: 0; top: 0; width: 100%; }
      #np .l { height: 50px; display: flex; align-items: baseline; gap: 14px; white-space: nowrap; opacity: 0; }
      #np .l b { font: 500 37px/50px var(--mono); letter-spacing: -0.02em; color: var(--ink); font-weight: 500; }
      #np .l i { font: 500 37px/50px var(--sans); font-style: normal; letter-spacing: -0.012em; color: var(--mute); }
    </style>
    <div id="np" class="card">
      <div class="hd" id="np-hd"></div>
      <div class="ck" id="np-ck"></div>
      <div class="run" id="np-run"></div>
      <hr>
      <div class="ls" id="np-ls"></div>
    </div>
    <script>
      // Generated by scripts/build.mjs. Tool names and recipients only, never message text.
      (function () {
        const M = MOVES, TITLES = ${JSON.stringify(T.titles)}, RUNS = ${JSON.stringify(runs)};
        const tl = gsap.timeline({ paused: true });
        // Anything cued at 0 is on the first frame, which is also the poster.
        const enter = (el, at, o) => (at <= 0 ? gsap.set(el, { opacity: 1 }) : M.enter(tl, el, at, o));
        const hd = document.getElementById("np-hd"), run = document.getElementById("np-run"), ls = document.getElementById("np-ls");
        const ck = document.getElementById("np-ck");
        // Heading and clock: each new one replaces the last. The clock steps like a machine.
        let ph = null, pc = null;
        TITLES.forEach((t) => {
          if (!ph || ph.textContent !== t.title) {
            const h = document.createElement("span"); h.textContent = t.title; hd.appendChild(h);
            if (ph) M.exit(tl, ph, t.at, { dur: 0.2, rise: 12, blur: 4 });
            enter(h, t.at + (ph ? 0.12 : 0), { dur: 0.3, rise: 16 });
            ph = h;
          }
          const c = document.createElement("span"); c.textContent = t.clock; ck.appendChild(c);
          if (pc) tl.to(pc, { opacity: 0, y: -24, filter: "blur(3px)", duration: 0.16, ease: "none" }, t.at);
          if (!pc) gsap.set(c, { opacity: 1 });
          else tl.fromTo(c, { opacity: 0, y: 24, filter: "blur(3px)" }, { opacity: 1, y: 0, filter: "blur(0px)", duration: 0.16, ease: "none", immediateRender: false }, t.at + 0.08);
          pc = c;
        });
        // Runs: a new run clears the list; older lines in a run turn mute as new ones type on.
        let prevBox = null, prevRun = null;
        RUNS.forEach((r) => {
          const box = document.createElement("div"); ls.appendChild(box);
          const rl = document.createElement("span"); rl.textContent = r.run + " run · " + r.case + " · Baari-eval, 4 Oct"; run.appendChild(rl);
          if (prevBox) { M.exit(tl, prevBox, r.at, { dur: 0.22, rise: 12, blur: 4 }); M.exit(tl, prevRun, r.at, { dur: 0.2, rise: 12 }); }
          enter(rl, r.at + (prevBox ? 0.12 : 0), { dur: 0.3, rise: 14 });
          const els = r.lines.map((c) => {
            const d = document.createElement("div"); d.className = "l";
            d.innerHTML = "<b></b>" + (c.to ? "<i></i>" : "");
            d.querySelector("b").textContent = c.op;
            if (c.to) d.querySelector("i").textContent = "→ " + c.to;
            box.appendChild(d); return d;
          });
          r.lines.forEach((c, i) => {
            enter(els[i], c.at, { dur: 0.3, rise: 16 });
            if (i > 0) tl.to(els[i - 1].querySelector("b"), { color: "#6B675F", duration: 0.3, ease: M.e }, c.at);
          });
          prevBox = box; prevRun = rl;
        });
        tl.set({}, {}, ${T.duration});
        window.__timelines["panel"] = tl;
      })();
    </script>
  </div>
</template>
`;
fs.writeFileSync("compositions/panel.html", panel);

const html = `<!doctype html>
<html lang="en">
<head>
<meta charset="UTF-8" />
<meta name="viewport" content="width=1920, height=1080" />
<title>Baari night</title>
<!-- Generated by scripts/build.mjs from timing.json. Edit timing.json, then rebuild. -->
<link rel="stylesheet" href="shared/theme.css" />
<style>
  html, body { width: 1920px; height: 1080px; overflow: hidden; background: var(--ground); }
  #root { position: relative; width: 100%; height: 100%; overflow: hidden; }
  #root > div[data-composition-src] { position: absolute; inset: 0; }
  .shot { position: absolute; inset: 0; overflow: hidden; }
  #foot { position: absolute; left: 0; right: 0; top: 960px; text-align: center; font: 500 37px/1.3 var(--sans); letter-spacing: -0.012em; color: var(--mute); z-index: 30; }
</style>
<script src="shared/vendor/gsap.min.js"></script>
<script src="shared/moves.js"></script>
<script src="timing.js"></script>
</head>
<body>
  <div id="root" data-composition-id="night" data-width="1920" data-height="1080" data-start="0" data-duration="${T.duration}">
${T.beats.map(beat).join("\n")}
    <div id="el-panel" data-composition-id="panel" data-composition-src="compositions/panel.html" data-start="0" data-duration="${T.duration}" data-track-index="4"></div>
    <div id="foot">App on demo data · tool calls from real runs on AgenticOrg, 4 October</div>
  </div>
  <script>
    window.__timelines["night"] = gsap.timeline({ paused: true });
  </script>
</body>
</html>
`;
fs.writeFileSync("index.html", html);
console.log(`index.html: ${T.beats.length} beats, ${T.duration}s, ${missing.length} placeholders; panel ${runs.map((r) => r.run + " " + r.lines.length).join(", ")}`);
