// Writes index.html, timing.js, compositions/stage.html and compositions/panel.html
// from timing.json and panel.json. The stage is the phone, which holds its place for
// the whole night (assets/phone.mp4, from scripts/phone.py), and the TV for the stamp.
// The panel types each real tool call like Base44's prompt box (film/LOOK.md).
// Run from film/deck/videos/night: node scripts/build.mjs [--final]
import fs from "node:fs";

const T = JSON.parse(fs.readFileSync("timing.json", "utf8"));
const P = JSON.parse(fs.readFileSync("panel.json", "utf8"));
const final = process.argv.includes("--final");
fs.writeFileSync("timing.js", `// Generated by scripts/build.mjs from timing.json.\nwindow.TIMING = ${JSON.stringify({ duration: T.duration, beats: T.beats })};\n`);
const tv = T.tv;
fs.writeFileSync("compositions/stage.html", `<template id="stage-template">
  <div data-composition-id="stage" data-width="1920" data-height="1080" data-duration="${T.duration}" style="position:absolute;inset:0">
    <style>
      /* One phone, right of the panel, the same size and place all night: it carries
         every cut (Base44, same framing, new state). The TV takes its place for the stamp. */
      #st-ph { left: 1128px; top: 103px; width: 393px; height: 820px; }
      #st-ph video { position: absolute; inset: 0; width: 100%; height: 100%; object-fit: cover; }
      #st-tv { left: 846px; top: 236px; width: 960px; height: 548px; visibility: hidden; }
      #st-tv video { position: absolute; inset: 0; width: 100%; height: 100%; object-fit: cover; }
    </style>
    <div class="shot">
      <div class="phone" id="st-ph"><div class="scr">
        <video id="st-pv" src="assets/phone.mp4" data-start="0" data-duration="${T.duration}" data-track-index="0" muted playsinline></video>
      </div></div>
      <div class="tv" id="st-tv"><div class="scr">
        <video id="st-tvv" src="${tv.src}" data-start="${tv.at}" data-duration="${tv.dur}" data-media-start="${tv.in}" data-track-index="1" muted playsinline></video>
      </div></div>
    </div>
    <script>
      (function () {
        const M = MOTION, tl = gsap.timeline({ paused: true });
        M.swap(tl, "#st-ph", "#st-tv", ${tv.at});
        M.swap(tl, "#st-tv", "#st-ph", ${tv.at + tv.dur});
        tl.set({}, {}, ${T.duration});
        window.__timelines["stage"] = tl;
      })();
    </script>
  </div>
</template>
`);

// The panel: each run's calls, quoted from panel.json, typed on at timing.json's times.
const runs = T.panel.map((r) => {
  const calls = P[r.run].calls;
  if (calls.length !== r.lines.length) throw new Error(`${r.run}: ${calls.length} calls in the trace, ${r.lines.length} times in timing.json`);
  return { run: r.run, at: r.at, case: P[r.run].case, lines: calls.map((c, i) => ({ op: c.op, to: c.to, at: r.lines[i] })) };
});
const panel = `<template id="panel-template">
  <div data-composition-id="panel" data-width="1920" data-height="1080" data-duration="${T.duration}" style="position:absolute;inset:0;pointer-events:none;z-index:30">
    <style>
      #np { position: absolute; left: 96px; top: 96px; width: 680px; height: 834px; padding: 44px 48px; border-radius: 28px; }
      #np .hd { position: relative; height: 72px; }
      #np .hd > span { position: absolute; left: 0; top: 0; font: 500 55px/1.09 var(--display); letter-spacing: -0.031em; color: var(--ink); white-space: nowrap; }
      #np-ck { position: absolute; right: 96px; top: 96px; height: 56px; width: 260px; z-index: 31; }
      #np-ck > span { position: absolute; right: 0; top: 0; font: 500 44px/56px var(--mono); letter-spacing: -0.02em; color: var(--ink); }
      #np .run { position: relative; height: 52px; margin-top: 16px; }
      #np .run > span { position: absolute; left: 0; top: 0; font: 500 37px/1.3 var(--sans); letter-spacing: -0.012em; color: var(--mute); white-space: nowrap; }
      #np hr { border: 0; height: 1px; background: var(--hair); margin: 22px 0 18px; }
      #np .ls { position: relative; }
      #np .ls > div { position: absolute; left: 0; top: 0; width: 100%; }
      #np .l { height: 50px; display: flex; align-items: baseline; gap: 14px; white-space: nowrap; }
      #np .l b { font: 500 37px/50px var(--mono); letter-spacing: -0.02em; color: var(--ink); font-weight: 500; }
      #np .l i { font: 500 37px/50px var(--sans); font-style: normal; letter-spacing: -0.012em; color: var(--mute); }
    </style>
    <div id="np-ck"></div>
    <div id="np" class="card">
      <div class="hd" id="np-hd"></div>
      <div class="run" id="np-run"></div>
      <hr>
      <div class="ls" id="np-ls"></div>
    </div>
    <script>
      // Generated by scripts/build.mjs. Tool names and recipients only, never message text.
      // Base44's prompt box: each call types on behind a cursor; the line before it turns
      // mute in 5 frames; headings, the run label and the clock change by hard cut.
      (function () {
        const M = MOTION, TITLES = ${JSON.stringify(T.titles)}, RUNS = ${JSON.stringify(runs)};
        const tl = gsap.timeline({ paused: true });
        // Anything cued at 0 is on the first frame, which is also the poster.
        const show = (el, at) => (at <= 0 ? gsap.set(el, { autoAlpha: 1 }) : M.cut(tl, el, at));
        const hd = document.getElementById("np-hd"), run = document.getElementById("np-run"), ls = document.getElementById("np-ls");
        const ck = document.getElementById("np-ck");
        let ph = null, pc = null;
        TITLES.forEach((t) => {
          if (!ph || ph.textContent !== t.title) {
            const h = document.createElement("span"); h.textContent = t.title; hd.appendChild(h); M.hide(h);
            if (ph) M.cut(tl, ph, t.at, false);
            show(h, t.at); ph = h;
          }
          const c = document.createElement("span"); c.textContent = t.clock; ck.appendChild(c); M.hide(c);
          if (pc) M.cut(tl, pc, t.at, false);
          show(c, t.at); pc = c;
        });
        let prevBox = null, prevRun = null;
        RUNS.forEach((r) => {
          const box = document.createElement("div"); ls.appendChild(box); M.hide(box);
          const rl = document.createElement("span"); rl.textContent = r.run + " run · " + r.case + " · Baari-eval, 4 Oct"; run.appendChild(rl); M.hide(rl);
          if (prevBox) { M.cut(tl, prevBox, r.at, false); M.cut(tl, prevRun, r.at, false); }
          show(box, r.at); show(rl, r.at);
          const els = r.lines.map((c) => {
            const d = document.createElement("div"); d.className = "l";
            d.innerHTML = "<b></b>" + (c.to ? "<i></i>" : "");
            d.querySelector("b").textContent = c.op;
            if (c.to) d.querySelector("i").textContent = "→ " + c.to;
            box.appendChild(d); M.hide(d); return d;
          });
          r.lines.forEach((c, i) => {
            if (c.at <= 0) { gsap.set(els[i], { autoAlpha: 1 }); return; }
            M.cut(tl, els[i], c.at);
            const end = M.type(tl, els[i].querySelector("b"), c.at, { until: (r.lines[i + 1] || { at: c.at + 1.2 }).at });
            if (c.to) M.words(tl, M.wordsOf(els[i].querySelector("i")), end + M.TICK);
            if (i > 0) M.colour(tl, els[i - 1].querySelector("b"), c.at, { color: "#6B675F" });
          });
          prevBox = box; prevRun = rl;
        });
        tl.set({}, {}, ${T.duration});
        window.__timelines["panel"] = tl;
      })();
    </script>
  </div>
</template>
`;
fs.writeFileSync("compositions/panel.html", panel);

const html = `<!doctype html>
<html lang="en">
<head>
<meta charset="UTF-8" />
<meta name="viewport" content="width=1920, height=1080" />
<title>Baari night</title>
<!-- Generated by scripts/build.mjs from timing.json. Edit timing.json, then rebuild. -->
<link rel="stylesheet" href="shared/theme.css" />
<style>
  html, body { width: 1920px; height: 1080px; overflow: hidden; background: var(--ground); }
  #root { position: relative; width: 100%; height: 100%; overflow: hidden; }
  #root > div[data-composition-src] { position: absolute; inset: 0; }
  .shot { position: absolute; inset: 0; overflow: hidden; }
  #foot { position: absolute; left: 0; right: 0; top: 960px; text-align: center; font: 500 37px/1.3 var(--sans); letter-spacing: -0.012em; color: var(--mute); z-index: 30; }
</style>
<script src="shared/vendor/gsap.min.js"></script>
<script src="motion.js"></script>
<script src="timing.js"></script>
</head>
<body>
  <div id="root" data-composition-id="night" data-width="1920" data-height="1080" data-start="0" data-duration="${T.duration}">
    <div id="el-stage" data-composition-id="stage" data-composition-src="compositions/stage.html" data-start="0" data-duration="${T.duration}" data-track-index="1"></div>
    <div id="el-panel" data-composition-id="panel" data-composition-src="compositions/panel.html" data-start="0" data-duration="${T.duration}" data-track-index="4"></div>
    <div id="foot">App on demo data · tool calls from real runs on AgenticOrg, 4 October</div>
  </div>
  <script>
    window.__timelines["night"] = gsap.timeline({ paused: true });
  </script>
</body>
</html>
`;
fs.writeFileSync("index.html", html);
console.log(`index.html: ${T.duration}s; panel ${runs.map((r) => r.run + " " + r.lines.length).join(", ")}`);
