// Writes index.html and compositions/captions.html from timing.json.
// A shot with compositions/<id>.html mounts it; any other shot mounts the
// placeholder (CLIP_SLOTS.md section 4) so the animatic is timed end to end.
// Run from film/trailer: node scripts/build.mjs [--final]  (--final refuses placeholders)
//   --excerpt s08 [seconds]  also writes excerpt.html: that one shot from its start,
//   for a quick test render (hyperframes render -c excerpt.html)
import fs from "node:fs";

const T = JSON.parse(fs.readFileSync("timing.json", "utf8"));
const vo = JSON.parse(fs.readFileSync("assets/vo/manifest.json", "utf8"));
const BEAT = 60 / T.bpm;
const r3 = (x) => Math.round(x * 1000) / 1000;
const shots = T.shots.map((s) => ({ ...s, start: r3(s.beat * BEAT), dur: r3(s.beats * BEAT) }));
const end = r3(Math.max(...shots.map((s) => s.start + s.dur)));
const final = process.argv.includes("--final");
const missing = shots.filter((s) => !fs.existsSync(`compositions/${s.id}.html`));
if (final && missing.length) {
  console.error("placeholders left:", missing.map((s) => `${s.id} (${s.slot})`).join(", "));
  process.exit(1);
}
const at = (shotId, t) => r3(shots.find((s) => s.id === shotId).start + t);

// Captions: one centred line per spoken line, held words/3 + 1 s or to the line's end.
const caps = [];
for (const c of T.vo) {
  if (c.caption === false) continue;
  const m = vo[c.line];
  const text = c.sub || m.sub;
  const words = text.split(/\s+/).length;
  const len = c.trim ?? m.dur;
  caps.push({ t: at(c.shot, c.at), d: r3(Math.max(len + 0.25, words / 3 + 1)), text });
}
for (const c of T.captions_extra || []) caps.push({ t: at(c.shot, c.at), d: c.dur, text: c.text });
caps.sort((a, b) => a.t - b.t);
// a caption ends where the next one starts
caps.forEach((c, i) => { if (caps[i + 1] && c.t + c.d > caps[i + 1].t - 0.05) c.d = r3(caps[i + 1].t - 0.05 - c.t); });
fs.writeFileSync("captions.json", JSON.stringify(caps, null, 1));

const slot = (s) => {
  const has = fs.existsSync(`compositions/${s.id}.html`);
  const src = has ? `compositions/${s.id}.html` : "compositions/placeholder.html";
  const vars = has ? "" : ` data-variable-values='${JSON.stringify({ slot: s.slot, shows: s.shows.replace(/'/g, "’") })}'`;
  return `    <div id="el-${s.id}" data-composition-id="${s.id}" data-composition-src="${src}" data-start="${s.start}" data-duration="${s.dur}" data-track-index="1"${vars}></div>`;
};
const html = `<!doctype html>
<html lang="en">
<head>
<meta charset="UTF-8" />
<meta name="viewport" content="width=1920, height=1080" />
<title>Baari trailer</title>
<!-- Generated by scripts/build.mjs from timing.json. Edit timing.json, then rebuild. -->
<link rel="stylesheet" href="shared/theme.css" />
<link rel="stylesheet" href="trailer.css" />
<script src="shared/vendor/gsap.min.js"></script>
<script src="shared/moves.js"></script>
<script src="timing.js"></script>
<script src="shared/vendor/qrcode.js"></script>
</head>
<body>
  <div id="root" data-composition-id="trailer" data-width="1920" data-height="1080" data-start="0" data-duration="${end}">
${shots.map(slot).join("\n")}
    <div id="el-island" data-composition-id="island" data-composition-src="compositions/island.html" data-start="0" data-duration="${end}" data-track-index="4"></div>
    <div id="el-captions" data-composition-id="captions" data-composition-src="compositions/captions.html" data-start="0" data-duration="${end}" data-track-index="5"></div>
${fs.existsSync("assets/mix.wav") ? `    <audio id="mix" src="assets/mix.wav" data-start="0" data-duration="${end}" data-track-index="10" data-volume="1"></audio>\n` : ""}  </div>
  <script>
    window.__timelines["trailer"] = gsap.timeline({ paused: true });
  </script>
</body>
</html>
`;
fs.writeFileSync("index.html", html);
// Cue times for compositions: every timing number stays in timing.json.
const cues = Object.fromEntries(shots.map((s) => [s.id, { start: s.start, dur: s.dur, ...(s.cues || {}) }]));
fs.writeFileSync("timing.js", `// Generated by scripts/build.mjs from timing.json.\nwindow.TIMING = ${JSON.stringify({ bpm: T.bpm, beat: BEAT, cues })};\n`);
if (fs.existsSync("assets/mix.wav") === false) console.warn("no assets/mix.wav yet: index.html has no soundtrack");

const ex = process.argv.indexOf("--excerpt");
if (ex > 0) {
  const s = shots.find((x) => x.id === process.argv[ex + 1]);
  const len = r3(Math.min(s.dur, parseFloat(process.argv[ex + 2] || s.dur)));
  const one = html
    .replace(/<div id="root"[^>]*>/, `<div id="root" data-composition-id="trailer" data-width="1920" data-height="1080" data-start="0" data-duration="${len}">`)
    .replace(/    <div id="el-[\s\S]*?(?=  <\/div>\n  <script>)/, `    <div id="el-${s.id}" data-composition-id="${s.id}" data-composition-src="${fs.existsSync(`compositions/${s.id}.html`) ? `compositions/${s.id}.html` : "compositions/placeholder.html"}" data-start="0" data-duration="${len}" data-track-index="1"></div>\n`);
  fs.writeFileSync("excerpt.html", one);
  console.log(`excerpt.html: ${s.id}, first ${len}s`);
}

const capHtml = `<template id="captions-template">
  <div data-composition-id="captions" data-width="1920" data-height="1080" data-duration="${end}" style="position:absolute;inset:0;pointer-events:none;z-index:50">
    <div id="cap-wrap"></div>
    <script>
      // Generated by scripts/build.mjs: one plate per spoken line (captions.json).
      (function () {
        const CAPS = ${JSON.stringify(caps)};
        const wrap = document.getElementById("cap-wrap");
        const tl = gsap.timeline({ paused: true });
        CAPS.forEach((c, i) => {
          const el = document.createElement("div");
          el.className = "cap";
          el.textContent = c.text;
          el.style.opacity = "0";
          wrap.appendChild(el);
          tl.fromTo(el, { opacity: 0, y: 8 }, { opacity: 1, y: 0, duration: 0.2, ease: MOVES.e }, c.t);
          tl.to(el, { opacity: 0, duration: 0.15, ease: MOVES.x }, c.t + c.d - 0.15);
        });
        tl.set({}, {}, ${end});
        window.__timelines["captions"] = tl;
      })();
    </script>
  </div>
</template>
`;
fs.writeFileSync("compositions/captions.html", capHtml);
// The narrator island: one ink pill at top centre that carries cuts. Widths come
// from scripts/measure.mjs so the pill tweens between measured numbers.
const widths = fs.existsSync("assets/island-widths.json") ? JSON.parse(fs.readFileSync("assets/island-widths.json", "utf8")) : {};
const isl = (T.island || []).map((c) => {
  const h = c.hide ? "" : c.text + (c.sub ? ` <span class="sub">${c.sub}</span>` : "");
  if (h && !widths[h]) console.warn("island width missing, run scripts/measure.mjs:", h);
  return { t: at(c.shot, c.at), html: h, w: widths[h] || 300, kind: c.kind || "plain", hide: !!c.hide };
});
const islHtml = `<template id="island-template">
  <div data-composition-id="island" data-width="1920" data-height="1080" data-duration="${end}" style="position:absolute;inset:0;pointer-events:none;z-index:40">
    <style>
      #isl-row { position: absolute; left: 0; right: 0; top: 54px; display: flex; justify-content: center; }
      #isl { width: 70px; overflow: hidden; opacity: 0; transform-origin: 50% 50%; }
      #isl .ba { position: relative; z-index: 1; }
      #isl .txt { position: relative; flex: 1; height: 68px; }
      #isl .txt > span { position: absolute; left: 0; top: 0; line-height: 68px; opacity: 0; white-space: nowrap; }
      #isl .txt > span.shimmer .sub { color: inherit; }
    </style>
    <div id="isl-row"><div id="isl" class="island"><img class="ba" src="shared/img/baari-mark.png" alt=""><div class="txt" id="isl-txt"></div></div></div>
    <script>
      // Generated by scripts/build.mjs from timing.json "island".
      (function () {
        const M = MOVES, CUES = ${JSON.stringify(isl)};
        const PAD = 102, DOT = 70;
        const pill = document.getElementById("isl"), box = document.getElementById("isl-txt");
        const tl = gsap.timeline({ paused: true });
        let shown = false, prev = null;
        CUES.forEach((c, i) => {
          const next = CUES[i + 1] ? CUES[i + 1].t : ${end};
          if (prev) M.exit(tl, prev, c.t, { dur: 0.18, rise: 10, blur: 3 });
          if (c.hide) {
            tl.to(pill, { width: DOT, duration: 0.3, ease: M.e }, c.t + 0.05);
            tl.to(pill, { opacity: 0, scale: 0.6, duration: 0.25, ease: M.x }, c.t + 0.25);
            shown = false; prev = null;
            return;
          }
          const s = document.createElement("span");
          s.className = c.kind === "shimmer" ? "t shimmer" : "t";
          s.innerHTML = c.html;
          box.appendChild(s);
          if (!shown) {
            tl.fromTo(pill, { opacity: 0, scale: 0.6, width: DOT }, { opacity: 1, scale: 1, duration: 0.5, ease: M.s }, c.t);
            shown = true;
          }
          tl.to(pill, { width: c.w + PAD, duration: 0.45, ease: M.s }, c.t + 0.05);
          M.enter(tl, s, c.t + 0.14, { dur: 0.3, rise: 10, blur: 4 });
          // the shimmer sweeps like a machine, so it is the one linear move
          if (c.kind === "shimmer") tl.fromTo(s, { backgroundPosition: "100% 0" }, { backgroundPosition: "-50% 0", duration: 1.2, ease: "none", repeat: Math.max(0, Math.floor((next - c.t) / 1.2) - 1) }, c.t + 0.14);
          prev = s;
        });
        tl.set({}, {}, ${end});
        window.__timelines["island"] = tl;
      })();
    </script>
  </div>
</template>
`;
fs.writeFileSync("compositions/island.html", islHtml);
console.log(`index.html: ${shots.length} shots, ${end}s, ${missing.length} placeholders; ${caps.length} captions`);
